#============Database Properties===============

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hrms?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: blogUserApp
    
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8090