#============Database Properties===============

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hrms?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
  application:
    name: UserApp
    
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8081
  
security:
  oauth2:
    client:
      clientId: 2187434861383499
      clientSecret: 847a96479b25def711a497e0d1c02ca3
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me